const BOOKS = [
  {
    id: 1,
    isbn: "0553120441",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    format: "Paperback",
  },
  {
    id: 2,
    isbn: "0679889175",
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    format: "Paperback",
  },
  {
    id: 3,
    isbn: "9780857660282",
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    format: "Paperback",
  },
  {
    id: 4,
    isbn: "0553096095",
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    format: "Hardcover",
  },
  {
    id: 5,
    isbn: "05530962356",
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    format: "Hardcover",
  },
  {
    id: 6,
    isbn: "0553098976",
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    format: "Hardcover",
  },
  {
    id: 7,
    isbn: "0553093476",
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    format: "Hardcover",
  },
  {
    id: 8,
    isbn: "0553115634",
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    format: "Hardcover",
  },
  {
    id: 9,
    isbn: "0553115765",
    title: "A Court of Mist and Fury",
    author: "Sarah J. Maas",
    format: "Hardcover",
  },
  {
    id: 10,
    isbn: "05531324567",
    title: "A Court of Wings and Ruin",
    author: "Sarah J. Maas",
    format: "Hardcover",
  },
  {
    id: 11,
    isbn: "05531324511",
    title: "A Court of Silver Flames",
    author: "Sarah J. Maas",
    format: "Hardcover",
  },
];

export default BOOKS;
