/*
Largest Swap
Given a positive integer, find the largest number that could be generated by swapping only two digits at most once.

Example 1: 							
Input: 2736							
Output : 7236						
Explanation:							
If we swap the number 2 and the number			
7 then the generated number would be 			
the largest number.

Example 2:
Input : 432
Output : 432
Explanation:Here, no swap is required. The given number is already the largest.
*/
